### ISSUE TITLE
Name clashes?

### ISSUE THREAD

**Issue by samoht** [kayceesrk/ocaml-planet#1]
The modules in your projects all have very generic names. It would be better to either prefix them with something, or to pack them together. An somehow better way is to add prefix and make the modules privtate + adding a toplevel module for the public interface with module aliases:

```
pl_http.ml: <...>
pl_post.ml:<...>
planet.ml:
module Http = Pl_http
module Post = Pl_post
```

**Comment by kayceesrk** [comment]
Thanks for the suggestions! Updated the module names with prefix `pl_*`. In the oasis configuration, I've have all the `Pl_*` modules as InternalModules. I'm only able to access the Planet module from the package. Is this not sufficient to make them private and avoid Name clashes? See 837c372636bad105c7d03380b6fa9bd523852a50.

**Comment by samoht** [comment]
"internal modules" means you still install the `.cmx` but not the `.cmi`. So might have issues when linking. internal modules together. Adding a prefix helps, so that should now be fine.

**Comment by kayceesrk** [comment]
Great! Thanks.
