### ISSUE TITLE
Release for OCaml 5.0

### ISSUE THREAD

**Issue by gpetiot** [kayceesrk/ocaml-planet#10]
`river` depends on `ocamlnet` that is not compatible with OCaml 5, is that possible to replace this dependency or something else to make `river` available on the last compiler release?
Thanks, that would be very useful for ocaml.org!

**Comment by tmattio** [comment]
Absolutely!

I don't think @kayceesrk or myself will have time in the near future, but I'd be happy to review a PR.

**Comment by gpetiot** [comment]
I noticed there is already a branch (`500`) doing that, but I cannot push on it. It's building locally with ocaml 5.0 though.

**Comment by tmattio** [comment]
I've just released 0.4 which is compatible with OCaml 5 (thanks to @aantron). I'm closing this in anticipation of the merge of https://github.com/ocaml/opam-repository/pull/26848
